In [1]:
# First we import the module and start up the Matlab interpreter

import os
import numpy as np
from pace_neutrons import Matlab
m = Matlab()

Trying MATLAB version: 2022b (/mnt/ceph-training/course_materials/pace_env/lib/python3.11/site-packages/pace_neutrons/ctfs/pace_2022b.ctf))
Searching for Matlab 9.13 in /opt/matlab2021b
Searching for Matlab 9.13 in /opt
Trying MATLAB version: 2021b (/mnt/ceph-training/course_materials/pace_env/lib/python3.11/site-packages/pace_neutrons/ctfs/pace_2021b.ctf))
Searching for Matlab 9.11 in /opt/matlab2021b
Found Matlab 9.11 glnxa64 at /opt/matlab2021b
Interface opened
All features have moved to hor_config


!==================================================================!
!          ISIS utilities for visualization and analysis           !

All features have moved to hor_config

!==================================================================!
!                           Horace 4.0.0                           !

!------------------------------------------------------------------!
!   Visualisation of multi-dimensional neutron spectroscopy data   !

!           R.A. Ewings, A. Buts, M

We will now run through some examples in the "getting started" guide to Matlab (at: https://www.mathworks.com/help/matlab/getting-started-with-matlab.html ), and see how it changes in Python under `libpymcr`.

First we define some arrays ( https://www.mathworks.com/help/matlab/learn_matlab/matrices-and-arrays.html ). Note that Matlab functions such as `zeros`, `sin`, `inv` must be prefixed with an `m.` in `libpymcr`.

The Matlab commands are given in comments - you should translate them to the Python/libpymcr equivalent and run the cell.

For the transpose operation, you cannot use the `'` operator like in Matlab. You can either use `numpy` and the `.T` property or use the Matlab `transpose` function.

Note that in Matlab the `*` operator is matrix-multiplication which is the `@` operator in numpy, whereas the `.*` operator is simple element-wise multiplication (which in Python/numpy is the `*` operator).

Finally note that in Jupyter notebooks, you have to explicitly `print` variables to the screen.

In [2]:
#a = [1 3 5; 2 4 6; 7 8 10]
#z = zeros(5,1)
#a + 10
#sin(a)
#a'
#p = a*inv(a)
#p = a.*a
#a.^3
#A = [a,a]
#A = [a; a]
#sqrt(-1)
#c = [3+4i, 4+3j; -i, 10j]

In [3]:
a = [[1, 3, 5], [2, 4, 6], [7, 8, 10]]
print(a)

[[1, 3, 5], [2, 4, 6], [7, 8, 10]]


In [4]:
z = m.zeros(5,1)
print(z)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [5]:
print(np.array(a) + 10)
print(m.sin(a))
print(m.transpose(a))

p = a @ m.inv(a)
print(p)

[[11 13 15]
 [12 14 16]
 [17 18 20]]
[[ 0.84147098  0.14112001 -0.95892427]
 [ 0.90929743 -0.7568025  -0.2794155 ]
 [ 0.6569866   0.98935825 -0.54402111]]
[[ 1.  2.  7.]
 [ 3.  4.  8.]
 [ 5.  6. 10.]]
[[ 1.00000000e+00  2.66453526e-15  0.00000000e+00]
 [-1.77635684e-15  1.00000000e+00  0.00000000e+00]
 [ 1.77635684e-15 -8.88178420e-15  1.00000000e+00]]


In [6]:
p = np.array(a) * a  # Only one side of this operator need be an array
print(p)

[[  1   9  25]
 [  4  16  36]
 [ 49  64 100]]


In [7]:
print(np.array(a)**3)

[[   1   27  125]
 [   8   64  216]
 [ 343  512 1000]]


In [8]:
A = np.hstack( (a,a) )  # List also work, e.g. np.hstack( [a, a] )
print(A)

[[ 1  3  5  1  3  5]
 [ 2  4  6  2  4  6]
 [ 7  8 10  7  8 10]]


In [9]:
A = np.vstack( (a, a) )
print(A)

[[ 1  3  5]
 [ 2  4  6]
 [ 7  8 10]
 [ 1  3  5]
 [ 2  4  6]
 [ 7  8 10]]


In [10]:
print(m.sqrt(-1))  # Or use Numpy with explicit complex number, e.g. np.sqrt(-1+0j)

c = [[3+4j, 4+3j], [-1j, 10j]]  # Imaginary literal must be [number]j (i does not work)
print(c)

[[0.+1.j]]
[[(3+4j), (4+3j)], [(-0-1j), 10j]]


Now we run through the Array Indexing ( https://www.mathworks.com/help/matlab/learn_matlab/array-indexing.html ) examples:

In [11]:
#A = [1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]
#A(4,2)
#A(8)
#A(4,5) = 17
#A(1:3,2)
#A(3,:)
#B = 0:10:100

In [12]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(A)
print(A[3,1])
print(A.flatten('F')[7])
# A(4,2) and A(8) point to the same element, but Matlab uses column-major (Fortran-style)
# memory layout whereas numpy use row-major (C-style) memory layout, so to flatten it
# for indexing you have to speficy Fortran-style ('F').

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
14
14


In [13]:
# There is no easy way to extend a matrix by indexing outside its bounds in Python like in Matlab.
A = np.hstack((A, np.array([[0],[0],[0],[17]])))
print(A)

[[ 1  2  3  4  0]
 [ 5  6  7  8  0]
 [ 9 10 11 12  0]
 [13 14 15 16 17]]


In [14]:
# Slices/views work the same in Matlab and numpy, 
# except for the 0-based (numpy) vs 1-based (Matlab) indexing,
# and the range being exclusive of the final index (numpy) vs inclusive (Matlab)
# e.g. A[0:3] in Python means the elements A[0], A[1], A[2];
# whilst A(1:3) in Matlab means A(1), A(2), A(3);
print(A[:3,1])
print(A[2,:])

[ 2  6 10]
[ 9 10 11 12  0]


In [15]:
B = range(0,101,10)  # Note range is up to but excluding final value
print(list(B))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
